[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.22.2"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_BUILD_TIMESTAMP = "1775395871"

[[plugins]]
  package = "@netlify/plugin-nextjs"
